name: rivgraph
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - gdal<3.3
  - numpy
  - geopandas
  - scikit-image
  - opencv
  - networkx<2.7
  - matplotlib
  - pyproj
  - shapely==1.7.1
  - fiona
  - fastdtw
  - loguru  
