name: rivgraph
channels:
  - jschwenk
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - gdal
  - numpy
  - geopandas
  - scikit-image
  - opencv
  - networkx<2.7
  - matplotlib
  - pyproj
  - shapely==1.7.1
  - fiona
  - rivgraph
  - fastdtw
  - pip
  - pip:
    - loguru  
