# This workflow installs and tests the RivGraph package

name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'  # run workflow at 12AM on first day of each month

jobs:
  ubunutu-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge, defaults
      - uses: actions/checkout@v3
      - name: install RivGraph + dependencies, then unit test
        shell: bash -l {0}
        run: |
          mamba env create -q --file environment.yml
          conda activate rivgraph
          conda uninstall rivgraph
          pip install pytest pytest-timeout pytest-cov coveralls coverage
          python setup.py install
          coverage run -m pytest --cov-config=.coveragerc --cov=rivgraph/
          conda list

  windows-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: conda-forge, defaults
      - uses: actions/checkout@v3
      - name: install RivGraph + dependencies, then unit test
        shell: bash -l {0}
        run: |
          conda env create -q --file environment.yml
          conda activate rivgraph
          conda uninstall rivgraph
          pip install pytest pytest-timeout pytest-cov coveralls
          python setup.py install
          pytest --cov-config=.coveragerc --cov=rivgraph/
          conda list

  macos-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: [3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge, defaults
      - uses: actions/checkout@v3
      - name: install RivGraph + dependencies, then unit test
        shell: sh -l {0}
        run: |
          mamba env create -q --file environment.yml
          conda activate rivgraph
          conda uninstall rivgraph
          pip install pytest pytest-timeout pytest-cov coveralls
          python setup.py install
          pytest --cov-config=.coveragerc --cov=rivgraph/
          conda list
